# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agents.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'agents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61gents.proto\".\n\x0b\x43hatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\"7\n\x13\x43hatMessageProgress\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t2J\n\x0c\x41gentService\x12:\n\x12ProcessChatMessage\x12\x0c.ChatMessage\x1a\x14.ChatMessageProgress0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=16
  _globals['_CHATMESSAGE']._serialized_end=62
  _globals['_CHATMESSAGEPROGRESS']._serialized_start=64
  _globals['_CHATMESSAGEPROGRESS']._serialized_end=119
  _globals['_AGENTSERVICE']._serialized_start=121
  _globals['_AGENTSERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
